version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bdd/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - my_network

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - my_network

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: python_worker
    environment:
      REDIS_HOST: redis
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - redis

  scrapping:
    build:
      context: ./scrapping
      dockerfile: Dockerfile
    container_name: python_scrapper
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - redis
      - postgres

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"  # Port d'accès à Grafana
    volumes:
      - grafana_data:/var/lib/grafana  # Sauvegarde des données Grafana
    networks:
      - my_network
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Nom d'utilisateur par défaut
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Mot de passe par défaut
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:

networks:
  my_network:
    driver: bridge
