{
 "title": "Bitcoins (BTC)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Les 10 premières part du marché",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    name,\r\n    price\r\nFROM \r\n    cryptos  \r\nORDER BY \r\n    date desc,\r\n    price desc;\r\n"
    }
   ]
  },
  {
   "title": "Les 10 premières du marché",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    name,\r\n    price\r\nFROM \r\n    cryptos  \r\nORDER BY \r\n    date desc,\r\n    price desc\r\nLIMIT \r\n    10;"
    }
   ]
  },
  {
   "title": "Bitcoins (BTC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    price \r\nFROM \r\n    cryptos \r\nWHERE \r\n    symbol = 'BTC'\r\nORDER BY \r\n    date ASC;\r\n"
    }
   ]
  },
  {
   "title": "Ethereum (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    price \r\nFROM \r\n    cryptos \r\nWHERE \r\n    symbol = 'ETH'\r\nORDER BY \r\n    date ASC;\r\n"
    }
   ]
  },
  {
   "title": "BNB (BNB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    price \r\nFROM \r\n    cryptos \r\nWHERE \r\n    symbol = 'BNB'\r\nORDER BY \r\n    date ASC;\r\n"
    }
   ]
  },
  {
   "title": "Shiba Inu (SHIB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "dataset": "my_database",
     "rawSql": "SELECT \r\n    date,\r\n    price \r\nFROM \r\n    cryptos \r\nWHERE \r\n    symbol = 'SHIB'\r\nORDER BY \r\n    date ASC;\r\n"
    }
   ]
  }
 ]
}