server {
    listen 80;
    server_name coinsprophet.davrengifo.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    server_name coinsprophet.com www.coinsprophet.com;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
    }
}

server {
    listen 443 ssl;
    server_name coinsprophet.davrengifo.dev;

    ssl_certificate /etc/letsencrypt/live/coinsprophet.davrengifo.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/coinsprophet.davrengifo.dev/privkey.pem;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
